### ISSUE TITLE
Nox failing on nixpkgs' Travis

### ISSUE THREAD

**Issue by nckx** [madjar/nox#26]
(Let's start off by saying I know almost nothing about `pip`, so excuse me if I'm way off base.)

I recently encountered the following Travis failure: https://s3.amazonaws.com/archive.travis-ci.org/jobs/73236950/log.txt.

Could this be caused by a newer, incompatible version of the `click` library being installed?

**Comment by madjar** [comment]
Hello there

The problem seems to be that the `payload` dictionary does not contain a `title`. The payload is what we get from the github API so either the API changed, or this is a transient failure.

Is this problem systematic, or just from time to time? If it's just once in a while, it's a problem with the github API (and the absence of retry and/or good error reporting on my side).

**Comment by nckx** [comment]
*Sigh.*

It only affected a handful of PRs (I assumed that could be caused by phased updates or other cleverness), and I can't reproduce it on any of them. Transient failure it is.

*So we're back to the usual Travis false positive rate of slightly less than 100%. Yay.*

Sorry for bothering. Thanks for the help!

**Comment by madjar** [comment]
Is the false positive rate that bad? I have to confessed that I have stopped monitoring travis for some time, and I'm a really bad maintainer.

**Comment by nckx** [comment]
To be clear: false positive *failure alerts*. False positive *successes* would be a nightmare. Now it's merely very annoying. Annoying enough to be of very little value (to me; in nixpkgs; compared to 2014), hence the impulsive exaggeration. I must now locally (re)test more than 50% of PRs. That's too damn high. And I don't even merge that many PRs...

Not that it's anyone's fault - certainly not yours. Too many moving parts, and I don't see how they can be simplified/cached without introducing side effects like false positive successes. I'd be happily proven wrong, but lack the time to do anything about it.

Not to mention Travis doesn't seem happy about the supporting "legacy" infrastructure that Nix requires.
