### ISSUE TITLE
nox doesn't play nice with tmp

### ISSUE THREAD

**Issue by risicle** [madjar/nox#42]
One thing nox will do on a multi-user machine (where multiple users use nox) is collide on ownership of files created in `/tmp`. This would be workaroundable if nox heeded `TMPDIR` or the like, but it doesn't seem to (?), making things a bit of a pain.

**Comment by madjar** [comment]
I believe this has been fixed in this (as of yet unreleased) commit: https://github.com/madjar/nox/commit/944e8e198876401f0a1ae56bf5d02f238d9fa6f6

I'll be sure to make a release when I have time.
