### ISSUE TITLE
No tag for 0.0.5

### ISSUE THREAD

**Issue by lheckemann** [madjar/nox#58]
Which git rev does the tarball on pypi correspond to?

**Comment by calvertvl** [comment]
Based on the release date for it, it has to be 8ef05bfba44709b9b838169950234873a845b977.

**Comment by madjar** [comment]
I couldn't find the machine on which I did that release, so I tagged 8ef05bf. There was probably an additional commit that bumped the version number that was lost at some point, though.

Here it is: https://github.com/madjar/nox/releases/tag/0.0.5
