### ISSUE TITLE
--ff-only in git defaults breaks Nox

### ISSUE THREAD

**Issue by grantwwu** [madjar/nox#74]
I have `--ff-only` set as a default option for merge in my global gitconfig, which seems to break the `nox-review` here: https://github.com/madjar/nox/blob/f50bebb4783c60ab50875eb8383d921e2df014b7/nox/review.py#L148

Would using `--no-ff` be acceptable?  (i.e. is adding a new merge commit always acceptable?)

**Comment by matthewbauer** [comment]
Yeah that sounds like a good idea. There is now an option called ```--no-merge``` that you can try, I think it won't have this problem. (but we should definitely fix merging).
